REL.10.00.00.03. Compatible with: Processor SDK Linux for Edge AI 10.00.00

diff --git a/docker/Makefile b/docker/Makefile
--- a/docker/Makefile
+++ b/docker/Makefile
@@ -8,10 +8,14 @@ ROS_VER          ?= 2
 GPUS             ?= n
 
 # Robotics SDK version
-SDK_VER          = 9.2.0
-EDGEAI_VER       = 9.2.0.5
-TIVA_LIB_VER     ?= 9.2.0
-RPMSG_LIB_VER    ?= 0.6.6
+SDK_VER          ?= 10.0.0
+EDGEAI_VER       ?= 10.0.0.7
+TIVA_LIB_VER     ?= 10.0.0
+RPMSG_LIB_VER    ?= 0.6.7
+
+# Used in install_vision_apps_lib.sh, install_osrt_libs.sh, install_tidl_libs.sh
+REL_MAJOR        ?= 10_00_00
+SDK_VER_STR      ?= 10000005
 
 # Set the operating variables based on the ROS version specified
 ROS_DISTRO        = humble
@@ -28,33 +32,27 @@ ifeq ($(ROS_VER), 1)
 endif
 
 # set PLATFORM based on "uname -m"
-PLATFORM          = j7
-ARCH              = arm64v8
+PLATFORM         ?= j7
+ARCH             ?= arm64v8
 ifeq ($(shell uname -m), x86_64)
 	PLATFORM      = pc
 	ARCH          = x86_64
 endif
 
 WORK_PATH_HOST    = $(HOME)/$(WORK_DIR)
-REPO_PATH         = /opt/$(REPO_NAME)
-ifeq ($(PLATFORM), pc)
-	REPO_PATH     = $(WORK_PATH_HOST)/ros_ws/src/$(REPO_NAME)
+ifeq ($(PLATFORM), j7)
+	SDK_DIR      ?= /opt/$(REPO_NAME)
 endif
-ROS_SRC_DIR       = $(REPO_PATH)
+ifeq ($(PLATFORM), pc)
+	SDK_DIR      ?= $(WORK_PATH_HOST)/ros_ws/src/$(REPO_NAME)
+endif
 DATA_DIR          = $(WORK_PATH_HOST)/data
-DOCKER_DIR        = $(ROS_SRC_DIR)/docker
-SCRIPTS_DIR       = $(ROS_SRC_DIR)/docker/scripts
-DLRT_DIR          = /opt/dl_runtime
 
 ifeq ($(ROS_DOCKER_INTERNAL),)
 	USE_PROXY = 0
 else
 	USE_PROXY = 1
 endif
-
-# Environment variable list to pass to the Docker container
-ENV_FILE          = env_list.txt
-ENV_FILE_PATH     = $(DOCKER_DIR)/$(ENV_FILE)
 
 # Tarball filenames
 ROSBAG_ZED_FILE       = ros2-bag_zed1_2020_1109.tar.gz
@@ -75,15 +73,30 @@ VISLOC_DATA_URL       = $(URL_BASE)/$(VISLOC_DATA_FILE)
 LIDAR2D_LOC_URL       = $(URL_BASE)/$(LIDAR2D_FILE)
 CALIB_IMGS_URL        = $(URL_BASE)/$(CALIB_IMGS_FILE)
 
+# base URL for downloading dependency libs
+LIB_BASE_URL ?= https://software-dl.ti.com/jacinto7/esd/robotics-sdk/$(REL_MAJOR)/deps
+
 # IP address
-J7_IP_ADDR       := $(shell ifconfig | grep -A 1 'eth0' | tail -1 | awk '{print $$2}')
+J7_IP_ADDR := $(shell ifconfig | grep -A 1 'eth0' | tail -1 | awk '{print $$2}')
+
+# Define wget function with retry logic
+define wget_with_retry
+	@for i in {1..3}; do \
+		wget -O $1 $2 && break || echo "Download failed, retrying ($$i/3)..."; \
+		sleep 3; \
+	done
+	@if [ ! -f $1 ]; then \
+		echo "Failed to download $1 after 3 attempts."; \
+		exit 1; \
+	fi
+endef
 
 ## Set up environments on J7 host linux
 opkg_config:
-	$(SCRIPTS_DIR)/config_opkg_repo.sh
+	$(SDK_DIR)/docker/scripts/config_opkg_repo.sh
 
 ipk_install:
-	$(SCRIPTS_DIR)/install_tivision_apps_ipk.sh
+	$(SDK_DIR)/docker/scripts/install_tivision_apps_ipk.sh
 
 ip_show:
 	@echo "$(J7_IP_ADDR)"
@@ -93,11 +106,8 @@ info:
 	$(info WORK_DIR          = $(WORK_DIR))
 	$(info REPO_NAME         = $(REPO_NAME))
 	$(info WORK_PATH_HOST    = $(WORK_PATH_HOST))
-	$(info REPO_PATH         = $(REPO_PATH))
-	$(info ROS_SRC_DIR       = $(ROS_SRC_DIR))
+	$(info SDK_DIR           = $(SDK_DIR))
 	$(info DATA_DIR          = $(DATA_DIR))
-	$(info DOCKER_DIR        = $(DOCKER_DIR))
-	$(info SCRIPTS_DIR       = $(SCRIPTS_DIR))
 
 ## Docker
 # generate "docker build" script
@@ -105,13 +115,19 @@ docker_build:
 	@echo "#!/bin/bash"                                       >  $(TGT_NAME)
 	@echo "set -e"                                            >> $(TGT_NAME)
 	@echo "SECONDS=0"                                         >> $(TGT_NAME)
-	@echo "ROS_DISTRO=$(ROS_DISTRO)"                          >> $(TGT_NAME)
 	@echo "SDK_VER=$(SDK_VER)"                                >> $(TGT_NAME)
-	@echo "DOCKER_TAG=$(PLATFORM)-ros-\$$ROS_DISTRO-common:\$$SDK_VER" >> $(TGT_NAME)
+	@echo "ROS_DISTRO=$(ROS_DISTRO)"                          >> $(TGT_NAME)
 ifeq ($(PLATFORM), j7)
-	@echo "DOCKER_TAG2=$(PLATFORM)-ros-\$$ROS_DISTRO-\$$SOC:\$$SDK_VER" >> $(TGT_NAME)
+	@echo "DOCKER_TAG=robotics-sdk:\$$SDK_VER-\$$ROS_DISTRO-base" >> $(TGT_NAME)
 endif
-	@echo "DOCKER_DIR=$(DOCKER_DIR)"                          >> $(TGT_NAME)
+ifeq ($(PLATFORM), pc)
+	@echo "DOCKER_TAG=robotics-sdk:\$$SDK_VER-\$$ROS_DISTRO-viz" >> $(TGT_NAME)
+endif
+ifeq ($(PLATFORM), j7)
+	@echo "DOCKER_TAG2=robotics-sdk:\$$SDK_VER-\$$ROS_DISTRO-\$$SOC" >> $(TGT_NAME)
+endif
+	@echo "export SDK_DIR=$(SDK_DIR)"                         >> $(TGT_NAME)
+	@echo "DOCKER_DIR=\$$SDK_DIR/docker"                      >> $(TGT_NAME)
 	@echo ": \"\$${USE_PROXY:=$(USE_PROXY)}\""                >> $(TGT_NAME)
 	@echo "# modify the server and proxy URLs as requied"     >> $(TGT_NAME)
 	@echo "if [ \"\$${USE_PROXY}\" -ne \"0\" ]; then"         >> $(TGT_NAME)
@@ -124,9 +140,13 @@ endif
 	@echo "echo \"REPO_LOCATION = \$$REPO_LOCATION\""         >> $(TGT_NAME)
 	@echo "DST_DIR=$(WORK_PATH_HOST)/docker_src"              >> $(TGT_NAME)
 	@echo "EDGEAI_VER=$(EDGEAI_VER)"                          >> $(TGT_NAME)
+ifeq ($(PLATFORM), j7)
 	@echo "TIVA_LIB_VER=$(TIVA_LIB_VER)"                      >> $(TGT_NAME)
 	@echo "RPMSG_LIB_VER=$(RPMSG_LIB_VER)"                    >> $(TGT_NAME)
-	@echo "bash \$$DOCKER_DIR/scripts/prepare_docker_build.sh \$$DST_DIR \$$TIVA_LIB_VER \$$RPMSG_LIB_VER" >> $(TGT_NAME)
+	@echo ": \"\$${BASE_URL:=$(LIB_BASE_URL)}\""              >> $(TGT_NAME)
+	@echo "SDK_VER_STR=$(SDK_VER_STR)"                        >> $(TGT_NAME)
+endif
+	@echo "bash \$$DOCKER_DIR/scripts/prepare_docker_build.sh \$$DST_DIR" >> $(TGT_NAME)
 	@echo "cd $(WORK_PATH_HOST)"                              >> $(TGT_NAME)
 	@echo "if [ \"\$$(docker images -q \$$DOCKER_TAG 2> /dev/null)\" == \"\" ]; then" >> $(TGT_NAME)
 	@echo "    docker build \\"                                   >> $(TGT_NAME)
@@ -134,6 +154,7 @@ endif
 	@echo "        --build-arg USE_PROXY=\$$USE_PROXY \\"         >> $(TGT_NAME)
 	@echo "        --build-arg REPO_LOCATION=\$$REPO_LOCATION \\" >> $(TGT_NAME)
 	@echo "        --build-arg HTTP_PROXY=\$$HTTP_PROXY \\"       >> $(TGT_NAME)
+	@echo "        --build-arg BASE_URL=\$$BASE_URL \\"           >> $(TGT_NAME)
 ifeq ($(PLATFORM), pc)
 	@echo "        --build-arg EDGEAI_VER=\$$EDGEAI_VER \\"       >> $(TGT_NAME)
 endif
@@ -153,6 +174,8 @@ ifeq ($(PLATFORM), j7)
 	@echo "    --build-arg ROS_DISTRO=\$$ROS_DISTRO \\"       >> $(TGT_NAME)
 	@echo "    --build-arg SDK_VER=\$$SDK_VER \\"             >> $(TGT_NAME)
 	@echo "    --build-arg EDGEAI_VER=\$$EDGEAI_VER \\"       >> $(TGT_NAME)
+	@echo "    --build-arg BASE_URL=\$$BASE_URL \\"           >> $(TGT_NAME)
+	@echo "    --build-arg SDK_VER_STR=\$$SDK_VER_STR \\"     >> $(TGT_NAME)
 	@echo "    -f \$$DOCKER_DIR/Dockerfile.$(ARCH).ti_libs ./docker_src"  >> $(TGT_NAME)
 	@echo "echo \"Docker build -t \$$DOCKER_TAG2 completed!\"" >> $(TGT_NAME)
 endif
@@ -165,17 +188,18 @@ endif
 # generate "docker run" script
 docker_run:
 	@echo "#!/bin/bash"                                       >  $(TGT_NAME)
-	@echo "ROS_DISTRO=$(ROS_DISTRO)"                          >> $(TGT_NAME)
 	@echo "SDK_VER=$(SDK_VER)"                                >> $(TGT_NAME)
+	@echo "ROS_DISTRO=$(ROS_DISTRO)"                          >> $(TGT_NAME)
 ifeq ($(PLATFORM), j7)
-	@echo "DOCKER_TAG=$(PLATFORM)-ros-\$$ROS_DISTRO-\$$SOC:\$$SDK_VER" >> $(TGT_NAME)
+	@echo "DOCKER_TAG=robotics-sdk:\$$SDK_VER-\$$ROS_DISTRO-\$$SOC" >> $(TGT_NAME)
 endif
 ifeq ($(PLATFORM), pc)
-	@echo "DOCKER_TAG=$(PLATFORM)-ros-\$$ROS_DISTRO-common:\$$SDK_VER" >> $(TGT_NAME)
+	@echo "DOCKER_TAG=robotics-sdk:\$$SDK_VER-\$$ROS_DISTRO-viz" >> $(TGT_NAME)
 endif
 	@echo ": \"\$${USE_PROXY:=$(USE_PROXY)}\""                >> $(TGT_NAME)
 ifeq ($(PLATFORM), j7)
-	@echo "DOCKER_DIR=$(DOCKER_DIR)"                          >> $(TGT_NAME)
+	@echo "SDK_DIR=$(SDK_DIR)"                                >> $(TGT_NAME)
+	@echo "DOCKER_DIR=\$$SDK_DIR/docker"                      >> $(TGT_NAME)
 ifeq ($(ROS_VER), 1)
 	@echo "IP_ADDR=\$$(ifconfig | grep -A 1 'eth0' | tail -1 | awk '{print \$$2}')"       >> $(TGT_NAME)
 	@echo "if [[ ! \$$IP_ADDR =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\$$ ]]; then"             >> $(TGT_NAME)
@@ -194,11 +218,10 @@ endif
 	@echo "docker run -it --rm \\"                            >> $(TGT_NAME)
 	@echo "    -v $(WORK_PATH_HOST):/root/$(WORK_DIR) \\"     >> $(TGT_NAME)
 ifeq ($(PLATFORM), j7)
-	@echo "    -v $(REPO_PATH):$(REPO_PATH) \\"               >> $(TGT_NAME)
+	@echo "    -v $(SDK_DIR):/opt/robotics_sdk \\"            >> $(TGT_NAME)
 endif
 ifeq ($(PLATFORM), j7)
 	@echo "    -v $(WORK_PATH_HOST)/.ros:/root/.ros \\"       >> $(TGT_NAME)
-	@echo "    -v /opt/edgeai-gst-apps:/opt/edgeai-gst-apps \\"     >> $(TGT_NAME)
 	@echo "    -v /opt/imaging:/opt/imaging \\"               >> $(TGT_NAME)
 	@echo "    -v /opt/model_zoo:/opt/model_zoo \\"           >> $(TGT_NAME)
 endif
@@ -218,7 +241,7 @@ ifeq ($(PLATFORM), j7)
 ifeq ($(ROS_VER), 1)
 	@echo "    --env J7_IP_ADDR=\$$IP_ADDR \\"                >> $(TGT_NAME)
 endif
-	@echo "    --env-file \$$DOCKER_DIR/$(ENV_FILE) \\"       >> $(TGT_NAME)
+	@echo "    --env-file \$$DOCKER_DIR/env_list.txt \\"      >> $(TGT_NAME)
 	@echo "    --device-cgroup-rule='c 235:* rmw' \\"         >> $(TGT_NAME)
 endif
 ifeq ($(PLATFORM), pc)
@@ -260,19 +283,19 @@ rosbag_download: check_data_dir
 	@echo "[rosbag_download] Downloading ROSBAG files ..."
 	@rm -rf  $(DATA_DIR)/ros_bag
 	@mkdir -p $(DATA_DIR)/ros_bag
-	@wget -O $(DATA_DIR)/$(ROSBAG_ZED_FILE) "$(ROSBAG_ZED_URL)"
+	$(call wget_with_retry, $(DATA_DIR)/$(ROSBAG_ZED_FILE), $(ROSBAG_ZED_URL))
 	@echo "Extracting..."
 	@tar xzf $(DATA_DIR)/$(ROSBAG_ZED_FILE) -C $(DATA_DIR)/ros_bag
 	@rm -f $(DATA_DIR)/$(ROSBAG_ZED_FILE)
-	@wget -O $(DATA_DIR)/$(ROSBAG_6DPOSE_FILE) "$(ROSBAG_6DPOSE_URL)"
+	$(call wget_with_retry, $(DATA_DIR)/$(ROSBAG_6DPOSE_FILE), $(ROSBAG_6DPOSE_URL))
 	@echo "Extracting..."
 	@tar xzf $(DATA_DIR)/$(ROSBAG_6DPOSE_FILE) -C $(DATA_DIR)/ros_bag
 	@rm -f $(DATA_DIR)/$(ROSBAG_6DPOSE_FILE)
-	@wget -O $(DATA_DIR)/$(ROSBAG_HUMANPOSE_FILE) "$(ROSBAG_HUMANPOSE_URL)"
+	$(call wget_with_retry, $(DATA_DIR)/$(ROSBAG_HUMANPOSE_FILE), $(ROSBAG_HUMANPOSE_URL))
 	@echo "Extracting..."
 	@tar xzf $(DATA_DIR)/$(ROSBAG_HUMANPOSE_FILE) -C $(DATA_DIR)/ros_bag
 	@rm -f $(DATA_DIR)/$(ROSBAG_HUMANPOSE_FILE)
-	@wget -O $(DATA_DIR)/$(ROSBAG_ODRADAR_FILE) "$(ROSBAG_ODRADAR_URL)"
+	$(call wget_with_retry, $(DATA_DIR)/$(ROSBAG_ODRADAR_FILE), $(ROSBAG_ODRADAR_URL))
 	@echo "Extracting..."
 	@tar xzf $(DATA_DIR)/$(ROSBAG_ODRADAR_FILE) -C $(DATA_DIR)/ros_bag
 	@rm -f $(DATA_DIR)/$(ROSBAG_ODRADAR_FILE)
@@ -281,7 +304,7 @@ rosbag_download: check_data_dir
 vl_data_download: check_data_dir
 ifneq ($(SOC),am62a)
 	@echo "[vl_data_download] Downloading the VL data files ..."
-	@wget -O $(DATA_DIR)/$(VISLOC_DATA_FILE) "$(VISLOC_DATA_URL)"
+	$(call wget_with_retry, $(DATA_DIR)/$(VISLOC_DATA_FILE), $(VISLOC_DATA_URL))
 	@rm -rf  $(DATA_DIR)/visual_localization_data
 	@tar xzf $(DATA_DIR)/$(VISLOC_DATA_FILE) -C $(DATA_DIR)
 	@rm -f $(DATA_DIR)/$(VISLOC_DATA_FILE)
@@ -290,7 +313,7 @@ endif
 
 lidar2d_download: check_data_dir
 	@echo "[lidar2d_download] Downloading Lidar data ..."
-	@wget -O $(DATA_DIR)/$(LIDAR2D_FILE) "$(LIDAR2D_LOC_URL)"
+	$(call wget_with_retry, $(DATA_DIR)/$(LIDAR2D_FILE), $(LIDAR2D_LOC_URL))
 	@rm -rf  $(DATA_DIR)/lidar_2d
 	@tar xzf $(DATA_DIR)/$(LIDAR2D_FILE) -C $(DATA_DIR)
 	@rm -f $(DATA_DIR)/$(LIDAR2D_FILE)
@@ -298,7 +321,7 @@ lidar2d_download: check_data_dir
 
 calib_download: check_data_dir
 	@echo "[calib_download] Downloading camera calib data ..."
-	@wget -O $(DATA_DIR)/$(CALIB_IMGS_FILE) "$(CALIB_IMGS_URL)"
+	$(call wget_with_retry, $(DATA_DIR)/$(CALIB_IMGS_FILE), $(CALIB_IMGS_URL))
 	@rm -rf  $(DATA_DIR)/calib_imgs_example
 	@tar xzf $(DATA_DIR)/$(CALIB_IMGS_FILE) -C $(DATA_DIR)
 	@rm -f $(DATA_DIR)/$(CALIB_IMGS_FILE)
